name = "landing-page-portfolium"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "18"

[site]
BUILD_OUTPUT_DIRECTORY = ".next"

[env.production]
routes = [
  { pattern = "/.*", zone_name = "landing-page-portfolium" }
]